# Generated by Django 5.0 on 2024-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RungeKuttaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_values', models.TextField()),
                ('y_values', models.TextField()),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('xn', models.FloatField()),
                ('n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
